### ISSUE TITLE
Setting up nest thermostat

### ISSUE THREAD

**Issue by ChrisRG711** [sisimomo/MMM-NestRemoteThermostat#10]
I tired setting this up, but cannot figure out how to configre the thermostat to send what it needs to send to make this module work. Any docs or pointers?

**Comment by LuckyDuckTx** [comment]
I tried setting this up too. The docs aren't clear on how to get the `thermostatId`, or what else is needed.  Do I need to setup something on the thermostat side?

**Comment by sisimomo** [comment]
Hi!

Just to clarify:
Even though the module’s UI **looks similar to a Nest thermostat**, it doesn’t actually require a Nest thermostat, nor does it integrate directly with the Nest API. The module simply **displays whatever thermostat data you send to it**. You could use Nest, Ecobee, Home Assistant climate entities, Sinope thermostats (which is what *I* use), or anything else — the module doesn’t know or care where the data comes from.

Because of that, the module doesn’t configure your thermostat for you.
Instead, *your home automation system* is responsible for sending updates to MagicMirror in the expected format.

For example, in my setup I use **Home Assistant** and send updates to MagicMirror using an automation like this:

```yaml
# Home Assistant automation
alias: Update Magic Mirror Nest Thermostats
mode: parallel
max: 8

triggers:
  - entity_id:
      - climate.bathroom
      - climate.bedroom
      - climate.living_room
      - climate.office
    trigger: state
  - entity_id: climate.hvac
    id: hvac
    trigger: state

actions:
  - choose:
      - conditions:
          - condition: trigger
            id: hvac
        sequence:
          - data:
              thermostatId: "{{ trigger.entity_id }}"
              ambientTemperature: "{{ state_attr(trigger.entity_id, 'current_temperature') }}"
              targetTemperature: >
                {% if states(trigger.entity_id) != 'off' %}
                  {{ state_attr(trigger.entity_id, 'temperature') }}
                {% else %}
                  {{ state_attr(trigger.entity_id, 'current_temperature') }}
                {% endif %}
              state: >
                {% if states(trigger.entity_id) == 'heat_cool' %}
                  {{ 'heating' if state_attr(trigger.entity_id, 'current_temperature') < state_attr(trigger.entity_id, 'temperature') else 'cooling' }}
                {% elif states(trigger.entity_id) == 'fan_only' %}
                  fan
                {% elif states(trigger.entity_id) == 'cool' %}
                  cooling
                {% else %}
                  {{ states(trigger.entity_id) }}
                {% endif %}
              power: >
                {% if state_attr(trigger.entity_id, 'fan_mode') == 'quiet' %}
                  1
                {% elif state_attr(trigger.entity_id, 'fan_mode') in ['low', 'medium_low'] %}
                  2
                {% elif state_attr(trigger.entity_id, 'fan_mode') in ['medium', 'medium_high'] %}
                  3
                {% elif state_attr(trigger.entity_id, 'fan_mode') == 'high' %}
                  4
                {% elif state_attr(trigger.entity_id, 'fan_mode') == 'strong' %}
                  5
                {% endif %}
              icon: fan
              loading: false
            action: rest_command.magicmirror_nest_remote_thermostat
    default:
      - data:
          thermostatId: "{{ trigger.entity_id }}"
          ambientTemperature: "{{ state_attr(trigger.entity_id, 'current_temperature') }}"
          targetTemperature: >
            {% if states(trigger.entity_id) != 'off' %}
              {{ state_attr(trigger.entity_id, 'temperature') }}
            {% else %}
              {{ state_attr(trigger.entity_id, 'current_temperature') }}
            {% endif %}
          state: >
            {% if state_attr(trigger.entity_id, 'hvac_action') == 'heating' %}
              heating
            {% else %}
              off
            {% endif %}
          power: >
            {{ ((state_attr(trigger.entity_id, 'heat_level') | int) / 20) | round(0, 'ceil') }}
          icon: radiator
          loading: false
        action: rest_command.magicmirror_nest_remote_thermostat
```

Your setup will likely be different, but the idea is the same:
**you send thermostat state → the module displays it.**
